### ISSUE TITLE
README.markdown symlink causes errors on GitHub actions

### ISSUE THREAD

**Issue by wch** [rstudio/webdriver#63]
For example, in https://github.com/rstudio/shiny/pull/3212/checks?check_run_id=1579237460#step:9:814#62 

```
Downloading GitHub repo rstudio/webdriver@HEAD
rstudio-webdriver-039e2aa/README.markdown: Can't create '\\\\?\\C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\RtmpYpSxeM\\remotes18c2d733ed3\\rstudio-webdriver-039e2aa\\README.markdown'
tar.exe: Error exit delayed from previous errors.
```

Can we move the README.Rmd and generated README.md file to the top level of the repo?

**Comment by gaborcsardi** [comment]
> Can we move the README.Rmd and generated README.md file to the top level of the repo?

Sure.
