### ISSUE TITLE
Download a File

### ISSUE THREAD

**Issue by luis-zapata-b** [rstudio/webdriver#82]
Can i use Webdriver to download a file? How? And if not, what other thool can a ise to acces a webpage, locate a download button and download a file?.

**Comment by gaborcsardi** [comment]
You can locate a button, and click it, sure. E.g. 
https://github.com/rstudio/webdriver/blob/6fd73445dd7bf8adb5ca6cafac0181f48883c322/tests/testthat/test-elements.R#L28-L29

**Comment by luis-zapata-b** [comment]
> You can locate a button, and click it, sure. E.g.
> 
> https://github.com/rstudio/webdriver/blob/6fd73445dd7bf8adb5ca6cafac0181f48883c322/tests/testthat/test-elements.R#L28-L29

Thank you very much! But where do the saved file goes? To my "Downloads" folder?

**Comment by gaborcsardi** [comment]
You might get a download dialog, IDK.
