### ISSUE TITLE
Moving mouse positions up the screen not possible.

### ISSUE THREAD

**Issue by dooplicate** [rstudio/webdriver#83]
I do not see how it is possible to move a mouse up the screen with assert_count() disabling negative numbers by way of stopifnot(x >= 0) via moveMouseTo().  Therefore making any mouse movement a one-way proposition.  Unless there is a solution I am not aware of this appears to be a major issue.

**Comment by gaborcsardi** [comment]
This is probably a bug and `assert_count()` should just check that the number is an integer. Do you want to submit a pull request for this? (No pressure.)

**Comment by dooplicate** [comment]
I agree, or making assert_count less zealous. You are much better qualified though so I'll leave this to you sir, thanks! Looking forward to a fix.

**Comment by gaborcsardi** [comment]
Can you try the version that I just pushed?

**Comment by dooplicate** [comment]
Everything is working as intended now.  Thank you for the hasty reply!
